import MainLayout from "layouts/main-layout"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <MainLayout>{children}</MainLayout>
}
